sudo: false

language: node_js

node_js:
  - "stable"
  - "0.10"

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.1
      - cabal-install-1.22
      - happy
      - alex

env:
  matrix:
    - ELM_VERSION=master
    - ELM_VERSION=0.15.1

  global:
    - secure: "RY4A5Bj0tN7rscwPh6eDJUmf2qWW6lXPBQrD74vg3hB1ubloCRuoXvBD8evUSQg6Kb1D7Dqi3FNpZmt9In7Tiz3Xy6Vb4Q0pbh1r8rq97ZuFFbxzPVRL2QuyYuqQfvsfoal4NVxGyhfTaLh1tCC/G6CjCjGDRXFcqhcz+CR0cEI="

before_install:
  - export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH

install:
  - travis_retry cabal update
  - cd installers/npm
  - npm install

before_script:
  - cd ..

script:
  - npm install ./npm
  - node_modules/.bin/elm make --help
  - node_modules/.bin/elm repl --help
  - node_modules/.bin/elm package install --help
  - node_modules/.bin/elm reactor --help
  - runhaskell BuildFromSource.hs $ELM_VERSION
  - cd Elm-Platform/*
  - mkdir dist_binaries
  - cp .cabal-sandbox/bin/elm* dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/linux-x64.tar.gz
