
clone_folder: c:\projects\elm-platform

environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.10"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - node --version
  - npm --version
  - cd c:\projects\elm-platform
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:STACK_INSTALLER="x86_64"
      } Else {
        $env:STACK_INSTALLER="i386"
      }
  - curl -s -ostack.zip -L --insecure http://www.stackage.org/stack/windows-%STACK_INSTALLER%
  - 7z x stack.zip stack.exe
  - stack update
  - stack setup > nul
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor - see https://github.com/commercialhaskell/stack/blob/e1605b888953124737ecff1dae3c790fd2a537c6/appveyor.yml
  - echo "" | stack install cabal-install
  - set PATH=%PATH%;C:\Users\appveyor\AppData\Local\Programs\stack\i386-windows\ghc-7.10.2\bin
  - set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\local\bin
  - cabal update
  - ps: Install-Product node $env:nodejs_version
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - cd c:\projects\elm-platform\installers
  - runhaskell BuildFromSource.hs 0.15.1

test_script:
  - cd Elm-Platform\*
  - mkdir dist_binaries
  - cp .cabal-sandbox\bin\elm* dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/linux-x64.tar.gz

build: off
