
clone_folder: c:\projects\elm-platform

environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.10"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cd c:\projects\elm-platform
  - curl -s -oinstall_haskell.exe https://haskell.org/platform/download/7.10.2/HaskellPlatform-7.10.2-a-i386-setup.exe
  - install_haskell
  - dir
  - set PATH=%PATH%;c:\projects\elm-platform\haskell
  - ghc --version
  - runhaskell --version
  - cabal --version
  - cabal update --verbose
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version

test_script:
  - cd c:\projects\elm-platform\installers
  - runhaskell BuildFromSource.hs 0.15.1
  - cd Elm-Platform\*
  - mkdir dist_binaries
  - cp .cabal-sandbox\bin\elm* dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/linux-x64.tar.gz

build: off
