clone_folder: c:\projects\elm-platform

environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.10"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - choco install haskellplatform -version 7.10.2.0 -y
  - ghc --version
  - runhaskell --version
  - cabal --version
  - cabal update --verbose
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version

test_script:
  - cd c:\projects\elm-platform\installers
  - runhaskell BuildFromSource.hs 0.15.1
  - cd Elm-Platform\*
  - mkdir dist_binaries
  - cp .cabal-sandbox\bin\elm* dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/linux-x64.tar.gz

build: off
