environment:
  matrix:
  - nodejs_version: "0.10"
  # Installs whatever is the latest version of Node
  - nodejs_version: "0"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

test_script:
  - node --version
  - npm --version
  - npm install installers\npm
  - node_modules\.bin\elm-make --help
  - node_modules\.bin\elm-repl --help
  - node_modules\.bin\elm-package install --help
  - node_modules\.bin\elm-reactor --help
  - node_modules\.bin\elm make --help
  - node_modules\.bin\elm repl --help
  - node_modules\.bin\elm package install --help
  - node_modules\.bin\elm reactor --help

build: off
