
clone_folder: c:\projects\elm-platform

environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.10"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - node --version
  - npm --version
  - cd c:\projects\elm-platform
  - curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
  - 7z x stack.zip stack.exe
  - stack update
  - stack setup > nul
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor - see https://github.com/commercialhaskell/stack/blob/e1605b888953124737ecff1dae3c790fd2a537c6/appveyor.yml
  - echo "" | stack install cabal-install
  - ghc --version
  - runhaskell --version
  - cabal --version
  - cabal update --verbose
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version

test_script:
  - cd c:\projects\elm-platform\installers
  - runhaskell BuildFromSource.hs 0.15.1
  - cd Elm-Platform\*
  - mkdir dist_binaries
  - cp .cabal-sandbox\bin\elm* dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/linux-x64.tar.gz

build: off
