clone_folder: c:\projects\elm-platform

environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.10"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - cd c:\projects\elm-platform
  - curl -s -ocabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz > nul
  - 7z x cabal.tar -ocabal_installation > nul
  - cd cabal_installation
  - ren cabal-1.22.0.0-i386-unknown-mingw32.exe cabal.exe
  - set PATH=%PATH%;c:\projects\elm-platform\cabal_installation
  - cd c:\projects\elm-platform
  - curl -s -oghc.tar.xz -L https://www.haskell.org/ghc/dist/7.10.2/ghc-7.10.2-i386-unknown-mingw32.tar.xz
  - 7z x ghc.tar.xz > nul
  - 7z x ghc.tar > nul
  - set PATH=%PATH%;c:\projects\elm-platform\ghc-7.10.2\bin
  - ghc --version
  - runhaskell --version
  - cabal --version
  - cabal update

test_script:
  - cd c:\projects\elm-platform\installers
  - runhaskell BuildFromSource.hs 0.15.1
  - cd Elm-Platform\*
  - mkdir dist_binaries
  - cp .cabal-sandbox/bin/elm* dist_binaries
  - tar cvzf binaries.tar.gz dist_binaries
  - curl -T binaries.tar.gz -uelmtravis:$BINTRAY_API_KEY https://api.bintray.com/content/elmlang/elm-platform/npm/$ELM_VERSION/$ELM_VERSION/linux-x64.tar.gz

build: off
